DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
    CONSTRAINT user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(200) NOT NULL,
    is_available BOOLEAN DEFAULT TRUE NOT NULL,
    owner_id INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id INT PRIMARY KEY AUTO_INCREMENT,
    rental_start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    rental_end TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    booker_id INTEGER REFERENCES users(id) NOT NULL,
    item_id INTEGER REFERENCES items(id),
    status INTEGER
);

CREATE TABLE IF NOT EXISTS comments (
    id INT PRIMARY KEY AUTO_INCREMENT,
    item_id INTEGER REFERENCES items(id),
    author_id INTEGER REFERENCES users(id),
    comment_text VARCHAR(500),
    creation_date TIMESTAMP
);
